name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_API: ${{ secrets.CF_API }}
      CF_USERNAME: ${{ secrets.CF_USER }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}
    steps:
      - uses: actions/checkout@v2
      - name: Run CF Push
        run: docker build . --file Dockerfile --args target
