name: Release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      CF_API: ${{ secrets.CF_API }}
      CF_USERNAME: ${{ secrets.CF_USER }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}
    runs:
      using: "docker"
      image: "Dockerfile"
      args:
        - target
