name: Release

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CF_API: ${{ secrets.CF_API }}
      CF_USER: ${{ secrets.CF_USER }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build App with Gradle
        run: ./gradlew build

      - name: Build cf container
        run: docker build . --file deploy/Dockerfile --tag cf

      - name: Run cf push
        run: docker run -e CF_API -e CF_USER -e CF_PASSWORD -e CF_ORG -e CF_SPACE cf push
