name: Release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      CF_API: ${{ secrets.CF_API }}
      CF_USERNAME: ${{ secrets.CF_USER }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE }}
    steps:
      - uses: actions/checkout@v2
      - name: build cf container
        run: docker build . --file deploy/Dockerfile --tag cf
      - name: run cf target
        run: docker run cf target
